### ISSUE TITLE
ctl vm list fails with error "could not find a qemu installation on this machine"

### ISSUE THREAD

**Issue by stefanbucur** [dslab-epfl/chef#17] opened 2015-08-05 14:35 UTC
Here's the exact output of the command:

```
$ s2e/ctl vm list
[FAIL] could not find a qemu installation on this machine
```

**Comment by ayekat** [comment] 2015-08-05 20:40
I could not reproduce this behaviour on Ubuntu 14.04 - what is the output of this?

```
$ s2e/ctl env
```

If `CHEF_DOCKERIZED` is not set to 1, the code producing the failure should never be executed. This is a minor issue though, since resolving issue #16 will entirely remove this behaviour.

**Comment by stefanbucur** [comment] 2015-08-06 08:24
I looked up the source code and found this definition for `utils.DOCKERIZED`:

``` python
DOCKERIZED = os.environ.get('CHEF_DOCKERIZED', '1') == '1'
```

So I'm surprised that it actually does work for you, because this variable is actually `True` when the `CHEF_DOCKERIZED` env var is undefined. Are you using any script that sets this variable to an empty value?

In any case, you should remove all the Docker references from the code and simplify things whenever possible. Less is more! :smile:

**Closed as completed** 2015-08-06 10:37 UTC
